services:
  employee:
    container_name: employee
    build:
      context: .
      dockerfile: EmployeeDockerFile
    ports:
      - "1111:8081"
    volumes:
      - type: volume
        source: mydata
        target: /app/employee
    networks:
      - employeenetwork
  frontend:
    container_name: nodejscont
    build:
      context : ./app
      dockerfile : DockerfileNodejs
    ports:
        - "4444:3333"
    volumes:
      - type: volume
        source: mydata
        target: /app/frontend
    networks:
      - frontendnetwork
volumes:
  mydata:
networks:
  employeenetwork:
  frontendnetwork:


